### ISSUE TITLE
[Bug] Keras 2.0.6 & Tensorflow compatibility

### ISSUE THREAD

**Issue by ericnrobertson** [jhartford/DeepIV#6]
Some versions of tensorflow seem to be incompatible with Keras 2.0.6, unaddressed by pip installation listed in docs.

Traceback (most recent call last):
  File "/Exploratory/DeepIV.py", line 5, in <module>
    from deepiv.models import Treatment, Response
  File "/anaconda3/envs/deepiv/lib/python3.6/site-packages/deepiv/models.py", line 6, in <module>
    import deepiv.samplers as samplers
  File "/anaconda3/envs/deepiv/lib/python3.6/site-packages/deepiv/samplers.py", line 4, in <module>
    from keras import backend as K
  File "/anaconda3/envs/deepiv/lib/python3.6/site-packages/keras/__init__.py", line 4, in <module>
    from . import activations
  File "/anaconda3/envs/deepiv/lib/python3.6/site-packages/keras/activations.py", line 6, in <module>
    from .engine import Layer
  File "/anaconda3/envs/deepiv/lib/python3.6/site-packages/keras/engine/__init__.py", line 8, in <module>
    from .training import Model
  File "/anaconda3/envs/deepiv/lib/python3.6/site-packages/keras/engine/training.py", line 25, in <module>
    from .. import callbacks as cbks
  File "/anaconda3/envs/deepiv/lib/python3.6/site-packages/keras/callbacks.py", line 26, in <module>
    from tensorflow.contrib.tensorboard.plugins import projector
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by XingruiWang** [comment]
The implementation in TensorFlow 2 is almost finished, see [here](https://github.com/XingruiWang/DeepIV.git).

**Comment by jhartford** [comment]
@XingruiWang thank you so much for this!
